defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
  [entryPoints.traefik]
    address = ":8080"
    compress = true

[api]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "docker.localhost"
  watch = true
  exposedbydefault = false
